Add support for PKCS#1 keys
aaschmid/taskwarrior-java-client pull request #6
Opened 2020-01-13 03:48 UTC by bgregos

2020-01-13 04:05 UTC, bgregos commented
I see a good bit of low-hanging fruit for cleanup, I'll try to update this soon.

2020-01-17 16:59 UTC, aaschmid commented
@bgregos: Thanks for your changes. In sum I like them pretty much. I would appreciate some tests, though. But as I haven't had some myself, I thing I first need to provide some infrastructure for testing this.
Can you discuss my review points?

2020-01-17 17:00 UTC, aaschmid commented on src/main/java/de/aaschmid/taskwarrior/ssl/KeyStoreBuilder.java
> +            e.printStackTrace();
Why removed throwing the exception?

2020-01-17 17:00 UTC, aaschmid commented on src/main/java/de/aaschmid/taskwarrior/ssl/KeyStoreBuilder.java
> +        String privateKeyString = "----...";
The rest should go to a separate method.

2020-01-17 17:00 UTC, aaschmid commented on src/main/java/de/aaschmid/taskwarrior/ssl/KeyStoreBuilder.java
> +            pemReader = new PemReader(new InputStreamReader(new ByteArrayInputStream(privKeyBytes)));
Merge with the line above.

2020-01-17 17:00 UTC, aaschmid commented on src/main/java/de/aaschmid/taskwarrior/ssl/KeyStoreBuilder.java
> +            e.printStackTrace();
I prefer throwing an exception or logging it. What's your opinion?

2020-01-17 17:00 UTC, aaschmid commented on src/main/java/de/aaschmid/taskwarrior/ssl/KeyStoreBuilder.java
> +            throw new RuntimeException("Unsupported key type: " + privateKeyObject.getType());
`UnsupportedOperationException`?

2020-01-17 17:00 UTC, aaschmid commented on src/main/java/de/aaschmid/taskwarrior/ssl/KeyStoreBuilder.java
> +            e.printStackTrace();
;-)

2020-01-31 18:58 UTC, aaschmid requested changes
I am still not sure if I want to include such a "huge"(TM) library into my "core" application but maybe I will provide another version. There is one other possibility (see http://magnus-k-karlsson.blogspot.com/2018/05/how-to-read-pem-pkcs1-or-pkcs8-encoded.html) with the ugly tradeoff that it uses `sun.*` packages. Would they be available on android jdk?

2020-01-31 18:58 UTC, aaschmid commented on build.gradle
> +    implementation group: 'org.bouncycastle', name: 'bcprov-jdk15on', version: '1.60'
Would it also be possible to use very much smaller `bcpkix-jdk15on` artifact?

2020-01-31 20:38 UTC, aaschmid commented on build.gradle
> +    implementation group: 'org.bouncycastle', name: 'bcprov-jdk15on', version: '1.60'
I would also prefer to create a shadow jar including BC using https://imperceptiblethoughts.com/shadow/

2020-02-01 12:13 UTC, aaschmid commented
And it would be nice to sign-off your commits as stated in https://github.com/aaschmid/taskwarrior-java-client/blob/master/CONTRIBUTING.md and agree the terms of the license agreement. Thanks @bgregos

2020-02-01 12:50 UTC, aaschmid commented on build.gradle
>      implementation group: 'org.bouncycastle', name: 'bcprov-jdk15on', version: '1.60'
I need to use `org.bouncycastle:bcpkix-jdk15on` to satisfy all used classes in your code.

2020-02-01 13:21 UTC, aaschmid commented
Maybe you can already rebase your changes onto https://github.com/aaschmid/taskwarrior-java-client/tree/pkcs1.and.pem.support.%232. That would be very helpful @bgregos. But please give me a hint if I should do myself :-)

2020-02-08 15:14 UTC, merged

2020-02-08 15:17 UTC, aaschmid commented
@bgregos: I merged your branch into a branch of mine in order to use your changes to my code for a version use bouncycastle for support of PKCS#1 keys. I would be very nice if you could agree the terms of the license agreement as in https://github.com/aaschmid/taskwarrior-java-client/blob/master/CONTRIBUTING.md. Thanks!

2020-02-14 18:42 UTC, bgregos commented
Hello, apologies for the delay. I hereby agree to the terms of the Taskwarrior Java client License Agreement. Thanks for your additions to the PR as well; let me know if anything else needs done in relation to this PR.

2020-02-14 19:12 UTC, aaschmid commented
Thanks, all the things are included in the version on Maven Central. 

I am actually curious about your results including the published version into your Android app :-)